version: 2

models:
  - name: stg_patients
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique

  - name: stg_admissions
    columns:
      - name: admission_id
        tests:
          - not_null
          - unique
      - name: patient_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_patients')
                field: patient_id

  - name: stg_claims
    columns:
      - name: claim_id
        tests:
          - not_null
          - unique
      - name: admission_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_admissions')
                field: admission_id

  - name: stg_labs
    columns:
      - name: lab_id
        tests:
          - not_null
          - unique
      - name: admission_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_admissions')
                field: admission_id

  - name: stg_pharmacy
    columns:
      - name: rx_id
        tests:
          - not_null
          - unique
      - name: admission_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_admissions')
                field: admission_id
