name: 'readmit_risk'
version: '1.0'
config-version: 2
profile: 'readmit_risk'

# Configuring how dbt should build my models
models:
  readmit_risk:
    core:
      +materialized: table   # all models in models/core/ will be tables
